### ISSUE TITLE
No such file or directory "racon"

### ISSUE THREAD

**Issue by vsoch** [TomHarrop/containers-sylabs-genomics#1]
hey @TomHarrop ! I'm putting together a Dockerfile for you, and just as a heads up, when I hit this line I get a "no such file or directory" when you target -C racon.

https://github.com/TomHarrop/containers-sylabs-genomics/blob/79333ffd380fb536ae21a2a86633972e2e9869cc/genomics/Singularity.racon_1.4.7#L43

It's probably trivial and not what was causing the issue, but just in case, wanted to point it out.

**Comment by TomHarrop** [comment]
Thanks! I don't think I had that problem building the Singularity image because I `mkdir racon` a few lines above.

**Comment by vsoch** [comment]
Ah that was my mistake then - I thought you were creating a base directory (when I do WORKDIR /racon) and didn't realize there were two levels. If something is amuck because of that when you test, let me know and we can fix it up. Although you could probably figure it out too :)

**Comment by TomHarrop** [comment]
OK - and I appreciate the help with the Dockerfile. I'll get it up on quay.io and pull it from there to Singularity.
